app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('instruktur/kelas/assign', function(){
// 	return view('instruktur.assignKelas');
// });

// Route::get('instruktur/prompt', function(){
// 	return view('instruktur.prompt');
// });

// Route::get('instruktur/prompt/create', function(){
// 	return view('instruktur.addPrompt');
// });




Route::get('change-avatar', [
    'as' => 'change-avatar',
    'uses' => 'Auth\AvatarController@index',
]);
Route::post('change-avatar/submit', [ 
    'as' => 'set-avatar',
    'uses' =>'Auth\AvatarController@set',
]);
// // Testing route above

Route::auth();

Route::get('change-password', [ 
    'as' => 'change-password',
    'uses' =>'Auth\ChangePasswordController@index',
]);
Route::post('set-password', [ 
    'as' => 'set-password',
    'uses' =>'Auth\ChangePasswordController@set',
]);


Route::get('/', 'HomeController@index');

Route::get('guide', 'PublicController@showGuide');

Route::get('publication', 'PublicController@showPublication');

Route::get('description', 'PublicController@showDescription');


Route::post('mahasiswa/store-balasan', [
    'as' => 'store-balasan-mahasiswa', 
    'uses' => 'Mahasiswa\JawabanController@storeBalasan'
]);

Route::post('mahasiswa/store-answer', [
    'as' => 'store-answer-mahasiswa', 
    'uses' => 'Mahasiswa\JawabanController@storeJawaban'
]);

Route::get('mahasiswa/kelas/{id}', [ 
    'as' => 'show-prompts-mahasiswa',
    'uses' =>'Mahasiswa\PromptController@showPrompts',
])->where('id', '[0-9]+');

Route::resource('mahasiswa/','Mahasiswa\PromptController');


// Baru single prompt mahasiswa

Route::post('mahasiswa/store-answer', [
    'as' => 'store.answer.mahasiswa', 
    'uses' => 'Mahasiswa\JawabanController@storeJawabanTemp'
]);

Route::get('mahasiswa/kelas/{id_kelas}/prompt/{id_prompt}', [ 
    'as' => 'show.single.prompt.mahasiswa',
    'uses' =>'Mahasiswa\SinglePromptController@showSinglePromptNew',
])->where('id_kelas', '[0-9]+');


// Baru single prompt instruktur

Route::get('instruktur/prompt/kelas/{id_kelas}/prompt/{id_prompt}', [ 
    'as' => 'show.single.prompt',
    'uses' =>'Instruktur\SinglePromptController@showSinglePromptNew',
])->where('id_kelas', '[0-9]+');

Route::get('instruktur/prompt/kelas/{id_kelas}/prompt/{id_prompt}/user/{id_user}', [ 
    'as' => 'show.single.prompt.user',
    'uses' =>'Instruktur\SinglePromptController@showSinglePromptUser',
])->where('id_kelas', '[0-9]+');

Route::post('instruktur/store-answer', [
    'as' => 'store.answer.instruktur', 
    'uses' => 'Instruktur\FeedbackController@storeAnswer'
]);




Route::post('instruktur/delete-prompt', [
    'as' => 'destroy-prompt', 
    'uses' => 'Instruktur\SinglePromptController@destroySinglePrompt'
]);

Route::get('instruktur/prompt/kelas/{id}', [ 
	'as' => 'show-prompts',
	'uses' =>'Instruktur\PromptController@showPrompts',
])->where('id', '[0-9]+');
Route::resource('instruktur/prompt','Instruktur\PromptController');




Route::post('instruktur/delete-mahasiswa/{id_user}/{id_kelas}', [
    'as' => 'destroy-mahasiswa', 
    'uses' => 'Instruktur\SingleKelasController@destroyMahasiswa'
]);
Route::post('instruktur/delete-kelas/{id_user}/{id_kelas}', [
    'as' => 'destroy-kelas', 
    'uses' => 'Instruktur\SingleKelasController@destroyKelas',
]);
Route::resource('instruktur/mahasiswa', 'Instruktur\MahasiswaController', ['parameters' => ['id' => 'id' ]]);




Route::get('instruktur/kelas/{id}/import-mahasiswa', [ 
    'as' => 'instruktur.kelas.import',
    'uses' =>'Instruktur\KelasController@import',
])->where('id', '[0-9]+');
Route::post('instruktur/kelas/storeImport', [
    'as' => 'instruktur.kelas.storeImport', 
    'uses' => 'Instruktur\KelasController@storeImport',
]);
Route::get('instruktur/kelas/{id}/tambah-mahasiswa', 'Instruktur\KelasController@addMahasiswa')->where('id', '[0-9]+');
Route::get('instruktur/kelas/{id}', 'Instruktur\KelasController@show')->where('id', '[0-9]+');
Route::get('instruktur/kelas/assign', 'Instruktur\KelasController@assignClass');
Route::resource('instruktur/kelas','Instruktur\KelasController');


Route::get('admin/mahasiswa/import', [ 
    'as' => 'admin.mahasiswa.import',
    'uses' =>'Admin\MahasiswaController@import',
]);
Route::post('admin/mahasiswa/storeImport', [
    'as' => 'admin.mahasiswa.storeImport', 
    'uses' => 'Admin\MahasiswaController@storeImport',
]);

Route::get('admin/instruktur/nonaktif', [
    'as' => 'admin.instruktur.nonaktif', 
    'uses' => 'Admin\InstrukturController@instrukturNonaktif',
]);

Route::get('admin/instruktur/activate/{id}', [
    'as' => 'admin.instruktur.activate', 
    'uses' => 'Admin\InstrukturController@activate',
]);


Route::resource('admin/kelas','Admin\KelasController');
Route::resource('admin/instruktur','Admin\InstrukturController');
Route::resource('admin/mahasiswa','Admin\MahasiswaController');
Route::resource('admin','Admin\AdminController');




// Register user (baru)

Route::get('register/user', 'CustomAuthController@showRegisterUser');
Route::get('register/mahasiswa', 'CustomAuthController@showRegisterMahasiswa');
Route::post('register/mahasiswa', 'CustomAuthController@registerMahasiswa');
Route::get('register/instruktur', 'CustomAuthController@showRegisterInstruktur');
Route::post('register/instruktur', 'CustomAuthController@registerInstruktur');

// Login new

Route::post('login/user', [
    'as' => 'login.custom', 
    'uses' => 'CustomAuthController@login',
]);

resources/views/admin/dashboard.blade.php
@extends('layouts.master')
@extends('layouts.header')
@extends('admin.sidebar-admin')

@section('title','| Dashboard Admin')

@section('content')
<div class="wrapper admin" data-page="Dashboard">
	<div class="content">
		<p>Selamat Datang Riandy Dimas B</p>
		<p class='text-smaller'>Saat ini Anda berada di Dashboard Admin</p>
		<p class='text-smaller'>Silakan klik menu di samping kiri untuk memulai</p>
	</div>
</div>
@stop

resources/views/admin/instruktur-nonaktif.blade.php
@extends('layouts.app')
@extends('admin.sidebar-admin')

@section('title','| Kelola Instruktur')

@section('content')
<div class="wrapper container" data-page="Instruktur">
  <h2>Daftar Instruktur Nonaktif</h2>

  @if(Session::has('flash_message'))
    <div class="alert alert-success">
      {{ Session::get('flash_message') }}
    </div>
  @endif
	<table id="example" class="table table-striped table-bordered" cellspacing="0" style="margin-top: 20px">
        <thead>
            <tr>
                <th>No</th>
                <th>Username</th>
                <th>Nama</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($datas as $index => $data)
            <tr>
                <td>{{ ($datas->perPage()*($datas->currentPage()-1))+($index+1) }}</td>
                <td>{{ $data->username }}</td>
                <td>{{ $data->name }}</td>
                <td>{{ $data->email }}</td>
                <td>
                  <a href="{{ url('/admin/instruktur/activate/'.$data->id) }}" class="btn btn-sm btn-primary"><i class="fa fa-check"></i> Aktifkan</a>
                </td>
            </tr>
         @endforeach
        </tbody>
    </table>
    {{ $datas->links() }}
</div>
@stop

resources/views/admin/instruktur.blade.php
@extends('layouts.app')
@extends('admin.sidebar-admin')

@section('title','| Kelola Instruktur')

@section('content')
<div class="wrapper container" data-page="Instruktur">
  <h2>Daftar Instruktur</h2>

  <a href="{{ url('admin/instruktur/nonaktif') }}" class="btn btn-success pull-right btn-green"><i class="fa fa-user"></i> Instruktur Nonaktif</a>
  <a href="{{ route('admin.instruktur.create') }}" class="btn btn-success pull-right btn-add btn-green"><i class="fa fa-plus"></i> Tambah Instruktur</a>
  @if(Session::has('flash_message'))
    <div class="alert alert-success">
      {{ Session::get('flash_message') }}
    </div>
  @endif
	<table id="example" class="table table-striped table-bordered" cellspacing="0" style="margin-top: 20px">
        <thead>
            <tr>
                <th>No</th>
                <th>Username</th>
                <th>Nama</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($datas as $index => $data)
            <tr>
                <td>{{ ($datas->perPage()*($datas->currentPage()-1))+($index+1) }}</td>
                <td>{{ $data->username }}</td>
                <td>{{ $data->name }}</td>
                <td>{{ $data->email }}</td>
                <td>
                  {!! Form::open([
                    'method' => 'DELETE',
                    'route' => ['admin.instruktur.destroy', $data->id]
                  ]) !!}
                  <a href="{{ route('admin.instruktur.edit', $data->id) }}" class="btn btn-sm btn-primary"><i class="fa fa-pencil fa-fw"></i> Ubah</a>
                  {!! Form::button('<i class="fa fa-trash"></i> Hapus', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm'] ) !!}
                  {!! Form::close() !!}
                </td>
            </tr>
         @endforeach
        </tbody>
    </table>
    {{ $datas->links() }}
</div>
@stop

resources/views/admin/kelas.blade.php
@extends('layouts.app')
@extends('admin.sidebar-admin')

@section('title','| Kelola Kelas')

@section('content')
<div class="wrapper container" data-page="Kelas">
  <h2>Daftar Kelas</h2>
  <a href="{{ route('admin.kelas.create') }}" class="btn btn-success pull-right btn-add btn-green"><i class="fa fa-plus"></i> Tambah Kelas</a>
  @if(Session::has('flash_message'))
    <div class="alert alert-success">
      {{ Session::get('flash_message') }}
    </div>
  @endif
  <table id="example" class="table table-striped table-bordered" cellspacing="0" style="margin-top: 20px">
    <thead>
        <tr>
            <th>No</th>
            <th>Nama Kelas</th>
            <th>Tahun Ajar</th>
            <th>Batch</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($datas as $index => $data)
      <tr>
        <td>{{ ($datas->perPage()*($datas->currentPage()-1))+($index+1) }}</td>
        <td>{{ $data->nama_kelas }}</td>
        <td>{{ $data->tahun_ajar_mulai }}</td>
        <td><span class="capitalize">{{ $data->batch }}</span></td>
        <td>
          {!! Form::open([
            'method' => 'DELETE',
            'route' => ['admin.kelas.destroy', $data->id]
          ]) !!}
          <a href="{{ route('admin.kelas.edit', $data->id) }}" class="btn btn-sm btn-primary"><i class="fa fa-pencil fa-fw"></i> Ubah</a>
          {!! Form::button('<i class="fa fa-trash"></i> Hapus', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm'] ) !!}
          {!! Form::close() !!}
        </td>
      </tr>
     @endforeach
    </tbody>
  </table>
  {{ $datas->links() }}
</div>
@stop

resources/views/admin/mahasiswa.blade.php
@extends('layouts.app')
@extends('admin.sidebar-admin')

@section('title','| Kelola Mahasiswa')

@section('content')
<div class="wrapper container" data-page="Mahasiswa">

  <h2>Daftar Mahasiswa</h2>
  <a href="{{ route('admin.mahasiswa.create') }}" class="btn btn-success pull-right btn-add btn-green"><i class="fa fa-plus"></i> Tambah</a>
  <a href="{{ route('admin.mahasiswa.import') }}" class="btn btn-success pull-right btn-add btn-green" style="margin-right: 5px"><i class="fa fa-upload"></i> Import</a>
  @if(Session::has('flash_message'))
  <div class="alert alert-success">
    {{ Session::get('flash_message') }}
  </div>
  @endif
	<table id="example" class="table table-striped table-bordered" cellspacing="0" style="margin-top: 20px">
        <thead>
            <tr>
                <th>No</th>
                <th>Identitas</th>
                <th>Username</th>
                <th>Nama</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($datas as $index => $data)
            <tr>
                <td>{{ ($datas->perPage()*($datas->currentPage()-1))+($index+1) }}</td>
                <td>{{ $data->no_identitas }}</td>
                <td>{{ $data->username }}</td>
                <td>{{ $data->name }}</td>
                <td>{{ $data->email }}</td>
                <td>
                  {!! Form::open([
                    'method' => 'DELETE',
                    'route' => ['admin.mahasiswa.destroy', $data->id]
                  ]) !!}
                  <a href="{{ route('admin.mahasiswa.edit', $data->id) }}" class="btn btn-sm btn-primary"><i class="fa fa-pencil fa-fw"></i> Ubah</a>
                  {!! Form::button('<i class="fa fa-trash"></i> Hapus', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm'] ) !!}
                  {!! Form::close() !!}
                </td>
            </tr>
         @endforeach
        </tbody>
    </table>
    {{ $datas->links() }}
</div>
@stop

resources/views/admin/sidebar-admin.blade.php
@section('sidebar')
@can('admin-access')
<div class="nav-side-menu">
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
        <div class="menu-list">
            <ul id="menu-content" class="menu-content collapse out side-nav">
				<li>
					<a href="{{ route('admin.index') }}"><span class="fa fa-fw fa-dashboard"></span> Dashboard</a>
				</li>
				<li>
					<a href="{{ route('admin.instruktur.index') }}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Instruktur</a>
				</li>
				<li>
					<a href="{{ route('admin.mahasiswa.index') }}"><span class="fa fa-users" aria-hidden="true"></span> Mahasiswa</a>
				</li>
				<li>
					<a href="/admin/kelas"><span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span> Kelas</a>
				</li>
{{--
                <li  data-toggle="collapse" data-target="#products" class="collapsed">
                  <a href="#"><i class="fa fa-gift fa-lg"></i> UI Elements <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="products">
                    <li class="active"><a href="#">CSS3 Animation</a></li>
                    <li><a href="#">General</a></li>
                    <li><a href="#">Buttons</a></li>
                    <li><a href="#">Tabs & Accordions</a></li>
                    <li><a href="#">Typography</a></li>
                    <li><a href="#">FontAwesome</a></li>
                    <li><a href="#">Slider</a></li>
                    <li><a href="#">Panels</a></li>
                    <li><a href="#">Widgets</a></li>
                    <li><a href="#">Bootstrap Model</a></li>
                </ul>


                <li data-toggle="collapse" data-target="#service" class="collapsed">
                  <a href="#"><i class="fa fa-globe fa-lg"></i> Services <span class="arrow"></span></a>
                </li>  
                <ul class="sub-menu collapse" id="service">
                  <li>New Service 1</li>
                  <li>New Service 2</li>
                  <li>New Service 3</li>
                </ul>


                <li data-toggle="collapse" data-target="#new" class="collapsed">
                  <a href="#"><i class="fa fa-car fa-lg"></i> New <span class="arrow"></span></a>
                </li>
                <ul class="sub-menu collapse" id="new">
                  <li>New New 1</li>
                  <li>New New 2</li>
                  <li>New New 3</li>
                </ul>


                 <li>
                  <a href="#">
                  <i class="fa fa-user fa-lg"></i> Profile
                  </a>
                  </li>

                 <li>
                  <a href="#">
                  <i class="fa fa-users fa-lg"></i> Users
                  </a>
                </li>
--}}
            </ul>
     </div>
</div>

{{--
<ul class="nav navbar-nav side-nav">
	<li>
		<a href="/home/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
	</li>
	<li>
		<a href="/admin/instruktur"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Instruktur</a>
	</li>
	<li>
		<a href="/admin/mahasiswa"><span class="fa fa-users" aria-hidden="true"></span> Mahasiswa</a>
	</li>
	<li>
		<a href="/admin/kelas"><span class="glyphicon glyphicon-blackboard" aria-hidden="true"></span> Kelas</a>
	</li>

	<li>
		<a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
		<ul id="demo" class="collapse">
			<li>
				<a href="#">Dropdown Item</a>
			</li>
			<li>
				<a href="#">Dropdown Item</a>
			</li>
		</ul>
	</li>
--}}
</ul>
@endcan
@stop