app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('instruktur/kelas/assign', function(){
// 	return view('instruktur.assignKelas');
// });

// Route::get('instruktur/prompt', function(){
// 	return view('instruktur.prompt');
// });

// Route::get('instruktur/prompt/create', function(){
// 	return view('instruktur.addPrompt');
// });




Route::get('change-avatar', [
    'as' => 'change-avatar',
    'uses' => 'Auth\AvatarController@index',
]);
Route::post('change-avatar/submit', [ 
    'as' => 'set-avatar',
    'uses' =>'Auth\AvatarController@set',
]);
// // Testing route above

Route::auth();

Route::get('change-password', [ 
    'as' => 'change-password',
    'uses' =>'Auth\ChangePasswordController@index',
]);
Route::post('set-password', [ 
    'as' => 'set-password',
    'uses' =>'Auth\ChangePasswordController@set',
]);


Route::get('/', 'HomeController@index');

Route::get('guide', 'PublicController@showGuide');

Route::get('publication', 'PublicController@showPublication');

Route::get('description', 'PublicController@showDescription');


Route::post('mahasiswa/store-balasan', [
    'as' => 'store-balasan-mahasiswa', 
    'uses' => 'Mahasiswa\JawabanController@storeBalasan'
]);

Route::post('mahasiswa/store-answer', [
    'as' => 'store-answer-mahasiswa', 
    'uses' => 'Mahasiswa\JawabanController@storeJawaban'
]);

Route::get('mahasiswa/kelas/{id}', [ 
    'as' => 'show-prompts-mahasiswa',
    'uses' =>'Mahasiswa\PromptController@showPrompts',
])->where('id', '[0-9]+');

Route::resource('mahasiswa/','Mahasiswa\PromptController');


// Baru single prompt mahasiswa

Route::post('mahasiswa/store-answer', [
    'as' => 'store.answer.mahasiswa', 
    'uses' => 'Mahasiswa\JawabanController@storeJawabanTemp'
]);

Route::get('mahasiswa/kelas/{id_kelas}/prompt/{id_prompt}', [ 
    'as' => 'show.single.prompt.mahasiswa',
    'uses' =>'Mahasiswa\SinglePromptController@showSinglePromptNew',
])->where('id_kelas', '[0-9]+');


// Baru single prompt instruktur

Route::get('instruktur/prompt/kelas/{id_kelas}/prompt/{id_prompt}', [ 
    'as' => 'show.single.prompt',
    'uses' =>'Instruktur\SinglePromptController@showSinglePromptNew',
])->where('id_kelas', '[0-9]+');

Route::get('instruktur/prompt/kelas/{id_kelas}/prompt/{id_prompt}/user/{id_user}', [ 
    'as' => 'show.single.prompt.user',
    'uses' =>'Instruktur\SinglePromptController@showSinglePromptUser',
])->where('id_kelas', '[0-9]+');

Route::post('instruktur/store-answer', [
    'as' => 'store.answer.instruktur', 
    'uses' => 'Instruktur\FeedbackController@storeAnswer'
]);




Route::post('instruktur/delete-prompt', [
    'as' => 'destroy-prompt', 
    'uses' => 'Instruktur\SinglePromptController@destroySinglePrompt'
]);

Route::get('instruktur/prompt/kelas/{id}', [ 
	'as' => 'show-prompts',
	'uses' =>'Instruktur\PromptController@showPrompts',
])->where('id', '[0-9]+');
Route::resource('instruktur/prompt','Instruktur\PromptController');




Route::post('instruktur/delete-mahasiswa/{id_user}/{id_kelas}', [
    'as' => 'destroy-mahasiswa', 
    'uses' => 'Instruktur\SingleKelasController@destroyMahasiswa'
]);
Route::post('instruktur/delete-kelas/{id_user}/{id_kelas}', [
    'as' => 'destroy-kelas', 
    'uses' => 'Instruktur\SingleKelasController@destroyKelas',
]);
Route::resource('instruktur/mahasiswa', 'Instruktur\MahasiswaController', ['parameters' => ['id' => 'id' ]]);




Route::get('instruktur/kelas/{id}/import-mahasiswa', [ 
    'as' => 'instruktur.kelas.import',
    'uses' =>'Instruktur\KelasController@import',
])->where('id', '[0-9]+');
Route::post('instruktur/kelas/storeImport', [
    'as' => 'instruktur.kelas.storeImport', 
    'uses' => 'Instruktur\KelasController@storeImport',
]);
Route::get('instruktur/kelas/{id}/tambah-mahasiswa', 'Instruktur\KelasController@addMahasiswa')->where('id', '[0-9]+');
Route::get('instruktur/kelas/{id}', 'Instruktur\KelasController@show')->where('id', '[0-9]+');
Route::get('instruktur/kelas/assign', 'Instruktur\KelasController@assignClass');
Route::resource('instruktur/kelas','Instruktur\KelasController');


Route::get('admin/mahasiswa/import', [ 
    'as' => 'admin.mahasiswa.import',
    'uses' =>'Admin\MahasiswaController@import',
]);
Route::post('admin/mahasiswa/storeImport', [
    'as' => 'admin.mahasiswa.storeImport', 
    'uses' => 'Admin\MahasiswaController@storeImport',
]);

Route::get('admin/instruktur/nonaktif', [
    'as' => 'admin.instruktur.nonaktif', 
    'uses' => 'Admin\InstrukturController@instrukturNonaktif',
]);

Route::get('admin/instruktur/activate/{id}', [
    'as' => 'admin.instruktur.activate', 
    'uses' => 'Admin\InstrukturController@activate',
]);


Route::resource('admin/kelas','Admin\KelasController');
Route::resource('admin/instruktur','Admin\InstrukturController');
Route::resource('admin/mahasiswa','Admin\MahasiswaController');
Route::resource('admin','Admin\AdminController');




// Register user (baru)

Route::get('register/user', 'CustomAuthController@showRegisterUser');
Route::get('register/mahasiswa', 'CustomAuthController@showRegisterMahasiswa');
Route::post('register/mahasiswa', 'CustomAuthController@registerMahasiswa');
Route::get('register/instruktur', 'CustomAuthController@showRegisterInstruktur');
Route::post('register/instruktur', 'CustomAuthController@registerInstruktur');

// Login new

Route::post('login/user', [
    'as' => 'login.custom', 
    'uses' => 'CustomAuthController@login',
]);

app/Http/Controllers/Admin/InstrukturController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Models\User;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Gate;
use Illuminate\Support\Facades\Auth;

class InstrukturController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth');
      if (Auth::check() && Gate::denies('admin-access')) {
        abort(403);
      }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $datas = User::orderBy('id', 'DESC')->where('role', 'instruktur')->where('status', '1')->paginate(8);
      return view('admin.instruktur')->with('datas', $datas);
    }

    public function instrukturNonaktif()
    {
      $datas = User::orderBy('id', 'DESC')->where('role', 'instruktur')->where('status', '0')->paginate(8);
      return view('admin.instruktur-nonaktif')->with('datas', $datas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('admin.auth.addUser')->with('role', 'instruktur');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $status = 1;
      $this->validate($request, [
        'role' => 'required',
        'name' => 'required|max:50',
        'username' => 'required',
        'password' => 'required|confirmed',
        'email' => 'required|unique:users,email|email',
      ]);

      User::create([
        'name' => $request['name'],
        'username' => $request['username'],
        'email' => $request['email'],
        'password' => bcrypt($request['password']),
        'role' => $request['role'],
        'status' => $status,
      ]);

      session()->flash('flash_message', 'User berhasil ditambahkan!');

      return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.auth.editUser')->with('data',$user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $user = User::findOrFail($id);
      if($user->email != $request->email) {
        $this->validate($request, [
          'name' => 'required|max:50',
          'email' => 'required|unique:users,email,$id,id|email',
        ]);
      } else {
        $this->validate($request, [
          'name' => 'required|max:50',
        ]);
      }

      $input = $request->all();

      $user->fill($input)->save();

      session()->flash('flash_message', 'Change(s) successfully saved!');

      return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $user = User::findOrFail($id);

      $user->delete();

      session()->flash('flash_message', 'User successfully deleted!');

      return redirect()->route('admin.instruktur.index');
    }

    public function activate($id)
    {
      User::where('id', $id)->update(['status' => 1]);

      session()->flash('flash_message', 'User telah diaktifkan!');

      return redirect()->route('admin.instruktur.nonaktif');
    }

   
}

app/Http/Controllers/Instruktur/FeedbackController.php
<?php

namespace App\Http\Controllers\Instruktur;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Jawaban;
use App\Models\Feedback;
use App\Models\FeedbackJawaban;
use Illuminate\Support\Facades\Auth;

class FeedbackController extends Controller
{
	  public function storeFeedback(Request $request)
    {
      $prompt = FeedbackJawaban::firstOrCreate([
        'id_jawaban' => $request['id_jawaban'],
        'id_feedback' => $request['feedback'],
      ]);

      session()->flash('flash_message', 'Feedback berhasil disimpan!');

      return redirect()->back();
    }

    public function storeAnswer(Request $request)
    {
      $jawaban = '';

      if ($request['feedback'] == null) {
          $jawaban = $request['jawaban'];
          $this->saveAnswer($request, $jawaban);    
      } else {
        $feedback = Feedback::where('id', $request['feedback'])->get()->first();
        $jawaban = $feedback->feedback_default;
        $this->saveAnswer($request, $jawaban);
      }

      session()->flash('flash_message', 'Balasan berhasil disimpan!');

      return redirect()->back(); 
    }

    public function saveAnswer(Request $request, $jawaban)
    {
        $prompt = new Jawaban;
        $prompt->id_user = Auth::user()->id;
        $prompt->id_user_sentTo = $request->id_user_sentTo;
        $prompt->id_prompt = $request->id_prompt;
        $prompt->jawaban = $jawaban;
        
        $prompt->save();

    }
}

app/Http/Controllers/Instruktur/KelasController.php
<?php

namespace App\Http\Controllers\Instruktur;

use Illuminate\Http\Request;

use App\Models\User;
use App\Models\Kelas;
use App\Models\KelasUser;

use App\Http\Requests;
use App\Http\Controllers\Controller;

Use Gate;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;

use DB;
use Excel;

class KelasController extends Controller
{
    public function __construct()
    {
      $this->middleware('auth');
      if (Auth::check() && Gate::denies('instruktur-access')) {
        abort(403);
      }
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $kelasUser = User::findOrFail(Auth::user()->id)->classes()->orderBy('nama_kelas','asc')->get();
      // $kelasList = $kelasUser->map(function ($item, $key){
      //   return $item->pivot->id_kelas;
      // });
      // $userKelas = Kelas::find(13)->users()->get();
      return view('instruktur.kelas', ['datas'=> $kelasUser]);
    }

    /**
     * Show the form for assigning class.
     *
     * @return \Illuminate\Http\Response
     */
    public function assignClass()
    {
      $kelas = Kelas::all();
      $kelasUser = User::findOrFail(Auth::user()->id)->classes()->get();
      $kelasDiff = $kelas->diff($kelasUser);
      $kelasDiffMap = $kelasDiff->each(function ($item, $key) {
        $item->nama_kelas = $item->nama_kelas . ' (' . $item->tahun_ajar_mulai . ' ' . ucfirst($item->batch) . ')';
      })->sortBy('nama_kelas')->pluck('nama_kelas','id');
     // $kelasDiff = $kelasDiff->pluck('nama_kelas','id');

      $mahasiswa = User::where('role','mahasiswa')->get();
      $mahasiswaMap = $mahasiswa ->each(function ($item, $key) {
        $item->name = $item->name . ' (' . $item->no_identitas . ')';
      })->sortBy('no_identitas')->pluck('name','id');

          // var data = [{ id: 0, text: 'enhancement' }, { id: 1, text: 'bug' }, { id: 2, text: 'duplicate' }, { id: 3, text: 'invalid' }, { id: 4, text: 'wontfix' }];
      return view('instruktur.assignKelas', ['kelas' => $kelasDiffMap, 'mahasiswa' => $mahasiswaMap]);
    }

    public function addMahasiswa($id)
    {
      $kelasUser = KelasUser::where('id_kelas', $id)->get();
      $isValid = $kelasUser->contains('id_user', Auth::user()->id);
      if (!$isValid) {
        abort(403);
      }

      $kelasInfo = Kelas::findOrFail($id);
      $userKelas = $kelasInfo->users()->where('role','mahasiswa')->orderBy('name','ASC')->get();
      $userAvailable = User::where('role','mahasiswa')->get()->diff($userKelas)->each(function ($item, $key) {
        $item->name = $item->name . ' (' . $item->no_identitas . ')';
      })->sortBy('name')->pluck('name','id');

      return view('instruktur.addMahasiswa', ['kelasInfo' => $kelasInfo, 'userAvailable' => $userAvailable]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      KelasUser::create([
        'id_user' => Auth::user()->id,
        'id_kelas' => $request['nama_kelas']
      ]);

      if($request['daftar_mahasiswa']){
        foreach ($request['daftar_mahasiswa'] as $key => $value) {
          $insert[] = [
            'id_user' => $value,
            'id_kelas' => $request['nama_kelas'] 
            ];
        }
        if(!empty($insert)){
          DB::table('kelas_users')->insert($insert);
        }
      }

      session()->flash('flash_message', 'Kelas berhasil ditambahkan!');

      return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $kelasUser = KelasUser::where('id_kelas', $id)->get();
      $isValid = $kelasUser->contains('id_user', Auth::user()->id);
      if (!$isValid) {
        abort(403);
      }
      
      $kelasInfo = Kelas::findOrFail($id);
      $userKelas = $kelasInfo->users()->where('role','mahasiswa')->orderBy('no_identitas','ASC')->paginate(8);
      return view('instruktur.singleKelas', ['kelasInfo' => $kelasInfo, 'userKelas' => $userKelas]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

    public function import($id)
    {
      $kelasUser = KelasUser::where('id_kelas', $id)->get();
      $isValid = $kelasUser->contains('id_user', Auth::user()->id);
      if (!$isValid) {
        abort(403);
      }

      $kelas = Kelas::findOrFail($id);

      return view('instruktur.importAssignMahasiswa', ['kelas' => $kelas]);
    }

    public function storeImport(Request $request)
    {
      $userAvailable = User::where('role','mahasiswa')->get();
      if(Input::hasFile('daftar_mahasiswa')){
        $path = Input::file('daftar_mahasiswa')->getRealPath();
        $data = Excel::load($path, function($reader) {
        })->get();
        if(!empty($data) && $data->count()){
          foreach ($data as $key => $value) {
            $username = $value->username;
            $userList = $userAvailable;
            $userId = $userList->flatten()->where('username', $username)->last()->id;
            $insert[] = ['id_user' => $userId, 'id_kelas' => $request['id_kelas'] ]; 
          }
         // dd($insert);
          if(!empty($insert)){
            DB::table('kelas_users')->insert($insert);
          }
        }
      }
      session()->flash('flash_message', 'Data successfully imported!');
      return back();
      /*
        - ambil seluruh data mahasiswa -> toArray
        - tentukan kelasnya -> getId
        - arrayOfMahasiswa -> whereIn (excel mahasiswa.npm)
        - $insert[](idKelas, idUser)
        - masukkin $insert [array of mahasiswa+kelas] ke db
      */
    }
}

resources/views/instruktur/addMahasiswa.blade.php
@extends('layouts.app')

@section('content')
	@section('title', ' | Tambah Mahasiswa')
	
	<div class="container" data-page="Kelas">
		<div class="row">
			<div class="large-panel col-md-12">
				<div class="page-info">
					<div class="page-info__title">{{$kelasInfo->nama_kelas}}</div>
					<div class="page-info__kelas">{{$kelasInfo->tahun_ajar_mulai}} {{$kelasInfo->batch}}</div>
				</div>
				@if(Session::has('flash_message'))
				    <div class="alert alert-success">
				        {{ Session::get('flash_message') }}
				    </div>
				@endif

				@if($errors->any())
			    <div class="alert alert-danger">
			        @foreach($errors->all() as $error)
			            <p>{{ $error }}</p>
			        @endforeach
			    </div>
				@endif
				
				@if(count($userAvailable) == 0)
					<div class="border">
						<h2 class="text-center">Tidak ada mahasiswa yang dapat ditambahkan ke kelas ini</h2>
					</div>
					<a href="{{ route('instruktur.kelas.show', $kelasInfo->id) }}" class="btn btn-default pull-right" style="margin-top: 5px"><i class="fa fa-chevron-left"></i> Kembali</a>
				@else
				{!! Form::open(array('route' => array ('instruktur.mahasiswa.store', $kelasInfo->id))) !!}

					{!! Form::hidden('nama_kelas', $kelasInfo->id) !!}
					<div class="form-group">
					    {!! Form::label('daftar_mahasiswa', 'Tambahkan Mahasiswa:', ['class' => 'control-label']) !!}
					    {!! Form::select('daftar_mahasiswa[]', $userAvailable, null, ['class' => 'form-control select-select2 select-textarea select2-daftar_mahasiswa', 'multiple' => 'multiple']); !!}
					</div>

					<button class="btn btn-primary" type="submit"><i class="fa fa-plus"></i> Tambah Mahasiswa</button>

					<a href="{{ route('instruktur.kelas.show', $kelasInfo->id) }}" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Kembali</a>

				{!! Form::close() !!}
				@endif
			</div>
		</div>
	</div>
@endsection

@section('script')
  {{-- import style2 script --}}
  <script src="{{asset('js/select2/select2.min.js')}}"></script>

  <script type="text/javascript">
		$(document).ready(function() {
			$.fn.select2.defaults.set("theme", "bootstrap");
		  $(".select-select2").select2();
		  $(".select2-daftar_mahasiswa").select2({
		  	allowClear: true,
		  	placeholder: "Pilih mahasiswa",
		  });
		});
	</script>
@endsection

resources/views/instruktur/addPrompt.blade.php
@extends('layouts.app')
@section('content')
	@section('title', ' | Tambah Prompt')
	<br/>
	<div class="container" data-page="Prompt">
		<div class="row">
			<div class="large-panel col-md-12">
			<h2>Tambah Prompt</h2>
			<br/>
			@if(Session::has('flash_message'))
			    <div class="alert alert-success">
			        {{ Session::get('flash_message') }}
			    </div>
			@endif
			@if($errors->any())
		    <div class="alert alert-danger">
		        @foreach($errors->all() as $error)
		            <p>{{ $error }}</p>
		        @endforeach
		    </div>
			@endif
				{!! Form::open(array('route' => 'instruktur.prompt.store')) !!}

					<div class="form-group">
				    {!! Form::label('id_kelas', 'Kelas:', ['class' => 'control-label']) !!}
				    {!! Form::select('id_kelas', $daftarKelas, null, ['class' => 'form-control select-select2']) !!}
					</div>

					<div class="form-group">
			    {!! Form::label('topik', 'Topik:', ['class' => 'control-label']) !!}
			    {!! Form::text('topik', null, ['class' => 'form-control', 'placeholder' => 'Tulis topik']) !!}
					</div>

					<div class="form-group">
			    {!! Form::label('pertanyaan', 'Pertanyaan:', ['class' => 'control-label']) !!}
			    {!! Form::textarea('pertanyaan', null, ['class' => 'form-control', 'placeholder' => 'Tulis pertanyaan prompt', 'rows' => 3]) !!}
					</div>

					<div class="form-group">
			    {!! Form::label('kata_kunci', 'Kata Kunci:', ['class' => 'control-label']) !!}
			    {!! Form::text('kata_kunci', null, ['class' => 'form-control', 'placeholder' => 'Tulis kata kunci prompt, pisahkan dengan titik koma (;)']) !!}
					</div>

					<div class="form-group">
			    {!! Form::label('feedback_default', 'Feedback Default:', ['class' => 'control-label']) !!}
			    {!! Form::textarea('feedback_default', null, ['class' => 'form-control', 'placeholder' => 'Tulis feedback yang mungkin Anda berikan, pisahkan dengan titik koma (;)', 'rows' => 3]) !!}
					</div>				

					<button class="btn btn-primary" type="submit"><i class="fa fa-plus"></i> Tambah Prompt</button>

					<a href="{{ route('instruktur.prompt.index') }}" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Kembali</a>

				{!! Form::close() !!}
			</div>
		</div>
	</div>
@endsection

@section('script')
<script src="{{asset('js/select2/select2.min.js')}}"></script>

<script type="text/javascript">
	$(document).ready(function() {
		$.fn.select2.defaults.set("theme", "bootstrap");
	  $(".select-select2").select2();
	  $("#chkbox-balasan").click(function (){
	  	$("#chkbox-balasan-value").prop("checked", !$("#chkbox-balasan-value").prop("checked"));
	  });
	});
</script>
@endsection

resources/views/instruktur/assignKelas.blade.php
@extends('layouts.app')

@section('content')

	@section('title','| Tambah Kelas')
	<br/>
	<br/>
	<div class="container" data-page="Kelas">
		
		<div class="row">
			<div class="large-panel col-md-12">
				<h2>Tambah Kelas</h2>
				<br/>
				@if(Session::has('flash_message'))
				    <div class="alert alert-success">
				        {{ Session::get('flash_message') }}
				    </div>
				@endif


				{!! Form::open(array('route' => 'instruktur.kelas.store')) !!}

					<div class="form-group">
					    {!! Form::label('nama_kelas', 'Nama Kelas:', ['class' => 'control-label']) !!}
					    {!! Form::select('nama_kelas', $kelas, null, ['class' => 'form-control select-select2']); !!}
					</div>

					<div class="form-group">
					    {!! Form::label('daftar_mahasiswa', 'Daftar Mahasiswa:', ['class' => 'control-label']) !!}
					    {!! Form::select('daftar_mahasiswa[]', $mahasiswa, null, ['class' => 'form-control select-select2 select-textarea select2-daftar_mahasiswa', 'multiple' => 'multiple']); !!}
					</div>

					<button class="btn btn-primary" type="submit"><i class="fa fa-plus"></i> Tambah Kelas</button>

					<a href="{{ route('instruktur.kelas.index') }}" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Kembali</a>

				{!! Form::close() !!}
				</div>
		</div>
	</div>

@endsection

@section('script')
  {{-- import style2 script --}}
  <script src="{{asset('js/select2/select2.min.js')}}"></script>

  <script type="text/javascript">
		$(document).ready(function() {
			$.fn.select2.defaults.set("theme", "bootstrap");
		  $(".select-select2").select2();
		  $(".select2-daftar_mahasiswa").select2({
		  	allowClear: true,
		  	placeholder: "Pilih mahasiswa"
		  });
		});
	</script>
@endsection

resources/views/instruktur/importAssignMahasiswa.blade.php
@extends('layouts.app')
@section('content')
	@section('title', ' | Import Mahasiswa')
	<br/>
	<div class="container" data-page="Kelas">
		<div class="row">
			<div class="large-panel col-md-12">
				<h2>Import Mahasiswa Kelas {{$kelas->nama_kelas}}</h2>
				<br/>
			@if(Session::has('flash_message'))
			    <div class="alert alert-success">
			        {{ Session::get('flash_message') }}
			    </div>
			@endif
			@if($errors->any())
		    <div class="alert alert-danger">
		        @foreach($errors->all() as $error)
		            <p>{{ $error }}</p>
		        @endforeach
		    </div>
			@endif
			<p>Untuk melakukan import data mahasiswa, pastikan Anda menggunakan file dengan format .csv. Di dalam file tersebut pastikan data dimulai dari header yang berada pada row pertama. Pastikan mahasiswa telah didaftarkan sebelumnya oleh administrator. Format header: NPM | username </p>
			<br>
			{!! Form::open(array('route' => 'instruktur.kelas.storeImport', 'files' => true)) !!}
				{!! Form::hidden('id_kelas', $kelas->id) !!}
				<div class="form-group">
						{!! Form::label('daftar_mahasiswa', 'File Daftar Mahasiswa:', ['class' => 'control-label']) !!}
				    {!! Form::file('daftar_mahasiswa', ['accept' => '.csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel']) !!}
				</div>

				<button class="btn btn-primary" type="submit"><i class="fa fa-upload"></i> Import Mahasiswa</button>

				<a href="{{ url('instruktur/kelas/' . $kelas->id) }}" class="btn btn-primary"><i class="fa fa-times"></i> Kembali</a>

			{!! Form::close() !!}
			</div>
		</div>
	</div>
@endsection

@section('script')
<script src="{{asset('js/select2/select2.min.js')}}"></script>

<script type="text/javascript">
	$(document).ready(function() {
		$.fn.select2.defaults.set("theme", "bootstrap");
	  $(".select-select2").select2();
	  $("#chkbox-balasan").click(function (){
	  	$("#chkbox-balasan-value").prop("checked", !$("#chkbox-balasan-value").prop("checked"));
	  });
	});
</script>
@endsection